name: Build and Push to GitHub Container Registry

on:
    push:
        branches:
            - master
        paths-ignore:
            # - ".github/**"
            # - ".github/*"
            - "README.md"
    workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read # Required to checkout the repository code
            packages: write # Required to publish packages to GHCR

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
              # The GITHUB_TOKEN secret is automatically created by GitHub Actions for each workflow run and has
              # permissions to publish packages associated with the workflow repository.

            - name: Define image tag for GHCR
              id: set_tag
              run: |
                  # Use the repository name from the GitHub context to form the GHCR image name.
                  # For example, if your repo is 'my-org/my-app', the image will be 'ghcr.io/my-org/my-app:1'.
                  IMAGE_NAME="ghcr.io/${{ github.repository }}:1"
                  echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT

            - name: Build and push Docker image (Multi-Platform)
              run: |
                  docker buildx build . \
                      --file Dockerfile \
                      --platform linux/amd64,linux/arm64,linux/arm/v7 \
                      --tag ${{ steps.set_tag.outputs.IMAGE_NAME }} \
                      --push
