name: Build and Push to GitHub Container Registry

on:
    push:
        branches:
            - master
        paths-ignore:
            # - ".github/**"
            # - ".github/*"
            - "README.md"
    workflow_dispatch:

jobs:
    publish-hello-world-image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            # - name: Build the Binary via Makefile
            #   run: docker build -t kuard-amd64:blue .

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile
                  platforms: linux/amd64 #,linux/arm64,linux/arm/v7
                  push: true
                  tags: zahlenhelfer/kuard:1

            # - name: Docker metadata
            #   id: meta
            #   uses: docker/metadata-action@v4
            #   with:
            #       images: ghcr.io/zahlenhelfer/kuard
            #       flavor: latest=true
            #       tags: |
            #           type=ref,event=branch
            #           type=ref,event=pr
            #           type=semver,pattern={{version}}

            # - name: Build and push
            #   uses: docker/build-push-action@v3
            #   with:
            #       context: .
            #       file: Dockerfile
            #       platforms: linux/amd64,linux/arm64,linux/arm/v7
            #       push: true
            #       #push: ${{ github.ref_type == 'tag' }}
            #       tags: ${{ steps.meta.outputs.tags }}
            #       labels: ${{ steps.meta.outputs.labels }}
